<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>
<?php $_activeFilters = $block->getLayer()->getState()->getFilters() ?>
<?php if ($block->canShowBlock()): ?>
    <div class="block filter">
        <div class="block-title filter-title <?php if ($_activeFilters): ?>is-set<?php endif ?>" data-mage-init='{"toggleAdvanced": {"toggleContainers": "#filter-content, body", "selectorsToggleClass": "filters-active"}}'>
            <span class="filter-title__text"><?php /* @escapeNotVerified */ echo __('Shop By') ?></span>
        </div>
    
        <div class="block-content filter-content" id="filter-content">
            <div class="filter-header">
                <div class="filter-header__back" data-mage-init='{"toggleAdvanced": {"toggleContainers": "#filter-content, body", "selectorsToggleClass": "filters-active"}}'><span><?php echo __('Back') ?></span></div>
                <span role="heading" aria-level="2" class="filter-header__title"><?php echo __('Filters') ?></span>
                <?php if ($_activeFilters): ?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                <?php endif; ?>
            </div>

            <?php echo $block->getChildHtml('state') ?>

            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if (!$wrapOptions): ?>
                    <div class="filter-options" id="narrow-by-list" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "multipleCollapsible": false}}'>
                <?php $wrapOptions = true; endif; ?>
                    <?php if ($filter->getItemsCount()): ?>
                    <div data-role="collapsible" class="filter-options__item">
                        <div data-role="title" aria-level="3" class="filter-options__title"><?php echo $block->escapeHtml(__($filter->getName())) ?></div>
                        <div data-role="content" class="filter-options__content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
                    </div>
                    <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
