<?php
// @codingStandardsIgnoreFile
?>
<!doctype html>
<html <?php /* @escapeNotVerified */ echo $htmlAttributes ?>>
    <head <?php /* @escapeNotVerified */ echo $headAttributes ?> data-block="app-head" data-bind="scope: 'app_head'">
        <?php /* @escapeNotVerified */ echo $requireJs ?>

        <!-- ko foreach: assetItems -->
            <!-- ko virtualHtml: $data --><!-- /ko -->
        <!-- /ko -->

        <!-- ko foreach: additionalItems -->
            <!-- ko virtualHtml: $data --><!-- /ko -->
        <!-- /ko -->

        <!-- ko if: !getProp('ready') -->
        <?php /* @escapeNotVerified */ echo $headContent ?>
        <?php /* @escapeNotVerified */ echo $headAdditional ?>
        <!-- /ko -->
    </head>
    <script type="text/x-magento-init">
    {
        "[data-block='app-head']": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "app_head": {
                        "component": "Meanbee_PWA/js/app/view/head"
                    }
                }
            }
        }
    }
    </script>
    <body data-container="body" data-mage-init='{"loaderAjax": {}, "loader": { "icon": "<?php /* @escapeNotVerified */ echo $loaderIcon; ?>"}}' <?php /* @escapeNotVerified */ echo $bodyAttributes ?>>
        <?php /* @escapeNotVerified */ echo $layoutContent ?>
    </body>
</html>
