<div data-block="app-content" data-bind="scope: 'content_block'">
    <div class="app__content-wrapper" data-bind="css: loadingStatus">
        <div class="loader"></div>
        <div class="app__content" id="app-content" data-bind="html: getValue()"></div>
    </div>
    <script type="text/x-magento-init">
    {
        "[data-block='app-content']": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "content_block": {
                        "component": "Meanbee_PWA/js/app/view/block",
                        "config": {
                            "options": {
                                "clean": true,
                                "cleanElement": "#app-content",
                                "key": "content"
                            }
                        }
                    }
                }
            }
        }
    }
    </script>
</div>