<div class="ajaxcart-flyout js-ajaxcart-flyout">
    <div class="ajaxcart-flyout__message js-ajaxcart-message"></div>

    <div class="ajaxcart-flyout__actions">
        <a href="<?php echo $block->getShoppingCartUrl() ?>" class="button button-secondary">
            <?php echo __('View Cart') ?>
        </a>
        <a href="<?php echo $block->getCheckoutUrl() ?>" class="button button-primary">
            <?php echo __('Checkout') ?>
        </a>
    </div>
</div>