<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block block-search">
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <span class="minisearch__trigger">
                <button type="button" class="icon" aria-label="<?php echo __('Search') ?>"><?php echo $block->getData('svgHelper')->getViewSvg('images/icons/search.svg') ?></button>
                <span class="minisearch__trigger-label"><?php echo __('Search') ?></span>
            </span>
            <div class="field search">
                <div class="minisearch__body" id="minisearch-body">
                    <div class="control">
                        <button type="button" class="minisearch__back" aria-label="<?php echo __('Back') ?>">
                            <?php echo $block->getData('svgHelper')->getViewSvg('images/icons/back.svg') ?>
                        </button>
                        <div class="minisearch__field">
                            <label class="label minisearch__field-label" for="search" data-role="minisearch-label">
                                <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                            </label>
                            <input id="search"
                                   data-mage-init='{"quickSearch":{
                                        "formSelector":"#search_mini_form",
                                        "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                        "destinationSelector":"#search_autocomplete",
                                        "template": "<li class=\"<%- data.row_class %>\" id=\"qs-option-<%- data.index %>\" role=\"option\"><span class=\"qs-option-name\"><% _(data.title).each(function(title) { if (title.match) { %><mark><%- title.string %><\/mark><% } else { %><%- title.string %><% } }) %><\/span><span aria-hidden=\"true\" class=\"amount\"><%- data.num_results %><\/span><\/li>"
                                        }
                                   }'
                                   type="search"
                                   name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                                   value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                                   placeholder="<?php /* @escapeNotVerified */ echo __('Search'); ?>"
                                   class="input-text"
                                   maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                                   role="combobox"
                                   aria-haspopup="false"
                                   aria-autocomplete="both"
                                   autocomplete="off"/>
                            <div id="search_autocomplete" class="search-autocomplete"></div>
                        </div>
                        <button type="button" class="minisearch__clear" aria-label="<?php echo __('Clear') ?>"><?php echo $block->getData('svgHelper')->getViewSvg('images/icons/clear.svg') ?></button>
                        <?php echo $block->getChildHtml() ?>
                    </div>
                    <div class="actions">
                        <button type="submit"
                                title="<?php echo $block->escapeHtml(__('Search')) ?>"
                                class="action search">
                            <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
