<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty">
    <?php echo $block->getChildHtml('checkout_cart_empty_widget'); ?>
    <h3 class="cart-empty-heading"><?php /* @escapeNotVerified */ echo __('Your cart is empty') ?></h3>
    <p><?php echo __('Sign in to view your cart or start shopping') ?></p>
    <div class="buttons-group">
        <a href="<?php echo $block->escapeUrl($block->getUrl('customer/account/login')) ?>" class="button"><?php echo __('Sign In') ?></a>
        <a href="<?php echo $block->escapeUrl($block->getContinueShoppingUrl()) ?>" class="button"><?php echo __('Continue Shopping') ?></a>
    </div>
    <?php echo $block->getChildHtml('shopping.cart.table.after'); ?>
</div>
