<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<span class="product-image-container">
    <span data-lazy class="product-image-wrapper placeholder__wrapper">
        <img class="product-image-photo placeholder__image"
            <?php /* @escapeNotVerified */ echo $block->getCustomAttributes(); ?>
             data-src="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
             width="<?php /* @escapeNotVerified */ echo $block->getResizedImageWidth(); ?>"
             height="<?php /* @escapeNotVerified */ echo $block->getResizedImageHeight(); ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>"/></span>
</span>
